
CREATE COLUMN TABLE "TSPNMIG"."ANTARA_TBL"  ( 
	KDHUBKEL 	NVARCHAR(2),
	NOTAS    	NVARCHAR(15),
	KDANTARA 	INTEGER,
	NIPANTARA	NVARCHAR(18) NOT NULL,
	NMTASPEN 	VARCHAR(80),
	NMANTARA 	VARCHAR(60),
	NIPTASPEN	VARCHAR(18),
	KDCABANG 	NVARCHAR(3) NOT NULL,
	KDSATKER 	NVARCHAR(20),
	UPDSTAMP 	TIMESTAMP,
	KDSSBP   	NVARCHAR(3) NOT NULL,
	KELSSBP  	NVARCHAR(1) NOT NULL,
	PRIMARY KEY(NIPANTARA,KDCABANG,KDSSBP,KELSSBP)
)
	UNLOAD PRIORITY 5;


CREATE COLUMN TABLE "TSPNMIG"."REF_JNSPREMI" 
	(
		"KDPREMI" INT CS_INT
		, "KET" VARCHAR(30) CS_STRING 
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_OTOSTRUK" 
	(
		"KDSTRUK" CHAR(2) CS_FIXEDSTRING NOT NULL
		, "NMSTRUK" VARCHAR(250) CS_STRING NOT NULL
		, PRIMARY KEY ( "KDSTRUK" ) 
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_MORTALITY" 
	(
		"USIA" INT CS_INT
		, "QX" DECIMAL(11	,8) CS_FIXED
		, "USERIN" INT CS_INT
		, "TIMESTMP" LONGDATE CS_LONGDATE
		, "LX" BIGINT CS_FIXED
		, "DX" BIGINT CS_FIXED
		, "WX" BIGINT CS_FIXED
		, "UX" BIGINT CS_FIXED 
	)
		UNLOAD PRIORITY 5 AUTO MERGE; 
CREATE COLUMN TABLE "TSPNMIG"."REF_FAKTOR_AKTUARIA" 
	(
		"KDFAKTOR" SMALLINT CS_INT NOT NULL
		, "NILAI" DOUBLE CS_DOUBLE 
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_PARAM" 
	(
		"KDPARAM" INT CS_INT
		, "KETERANGAN" VARCHAR(255) CS_STRING
		, "TGL" INT CS_INT 
	)
		UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_POS" 
	(
		"KODEPOS" NVARCHAR(10) NOT NULL 
		, "NOURUT" INTEGER CS_INT NOT NULL 
		, "NMKODEPOS" VARCHAR(80)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KODEPOS", "NOURUT")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_MEMFILE" 
	(
		"KDCABANG" NVARCHAR(3) NOT NULL 
		, "KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "TAHUN" SMALLINT CS_INT NOT NULL 
		, "NOVOUCHER" INTEGER CS_INT
		, "NOCEKPOS" INTEGER CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("TAHUN"	, "KDPRODUK", "KDCABANG")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_GROUP_BAYAR" 
	(
		"KDGROUP" NVARCHAR(2) NOT NULL 
		, "KDBENDAHARA" NVARCHAR(1) NOT NULL 
		, "KDCABANG" NVARCHAR(3) NOT NULL 
		, "NMGROUP" VARCHAR(60)
		, "FAX" VARCHAR(20)
		, "ALM_GROUP" VARCHAR(80)
		, "KOTA" VARCHAR(50)
		, "KODEPOS" VARCHAR(10)
		, "TELEPON" VARCHAR(20)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, "NOURUT" INTEGER CS_INT
		, PRIMARY KEY ("KDGROUP"		, "KDBENDAHARA"		, "KDCABANG")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_RUMAH_SAKIT" 
	(
		"KODE_RS_KLINIK_FASKES" CHAR(8) CS_FIXEDSTRING NOT NULL 
		, "TAT_PKS" DATE CS_DAYDATE
		, "KDCABANG" NVARCHAR(3)
		, "NAMA_RS_KLINIK_FASKES" VARCHAR(100)
		, "ALAMAT_RS_KLINIK_FASKES" VARCHAR(150)
		, "DATI1" CHAR(2) CS_FIXEDSTRING
		, "DATI2" CHAR(2) CS_FIXEDSTRING
		, "DATI3" CHAR(2) CS_FIXEDSTRING
		, "DATI4" CHAR(3) CS_FIXEDSTRING
		, "KDKANBYR" CHAR(4) CS_FIXEDSTRING
		, "JNSBAYAR" CHAR(2) CS_FIXEDSTRING
		, "KDGROUP" CHAR(2) CS_FIXEDSTRING
		, "KDBENDAHARA" CHAR(3) CS_FIXEDSTRING
		, "KDCABBYR" NVARCHAR(3)
		, "NMKANBYR" VARCHAR(60)
		, "NOREK" VARCHAR(33)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KODE_RS_KLINIK_FASKES")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_STATUS_WALI" 
	(
		"KDSTSWALI" SMALLINT CS_INT NOT NULL 
		, "KETERANGAN" VARCHAR(255) NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KDSTSWALI")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_THP" 
	(
		"KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "TMT_THPTBL" DATE CS_DAYDATE NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "PERSEN_PREMI" DECIMAL(7,2) CS_FIXED
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, PRIMARY KEY ("KDPRODUK"
		, "TMT_THPTBL"
		, "KDKELOMPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SUMBER_SPP" 
	(
		"KD_SUMBER_SPP" SMALLINT CS_INT
		, "NM_SUMBER_SPP" CHAR(40) CS_FIXEDSTRING
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_UKP" 
	(
		"KDUKP" SMALLINT CS_INT NOT NULL 
		, "NMUKP" CHAR(50) CS_FIXEDSTRING NOT NULL 
		, PRIMARY KEY ("KDUKP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_CASE" 
	(
		"KDCASE" SMALLINT CS_INT NOT NULL 
		, "NMCASE" VARCHAR(100)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, "INPUTER" VARCHAR(32)
		, PRIMARY KEY ("KDCASE")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KPRFEE" 
	(
		"TMT_EFEKTIF" DATE CS_DAYDATE NOT NULL 
		, "KDKELOMPOK" INTEGER CS_INT NOT NULL 
		, "NMKELOMPOK" VARCHAR(60) NOT NULL 
		, "KDAKTIV" INTEGER CS_INT DEFAULT 0 NOT NULL 
		, "TARIF_FEE" INTEGER CS_INT DEFAULT 0 NOT NULL 
		, "TGLPKS" DATE CS_DAYDATE
		, "NOMOR_PKS" VARCHAR(120)
		, "NAMAMITRA" VARCHAR(100)
		, "ALAMAT_MITRA" VARCHAR(200)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SYARATKLIM" 
	(
		"KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "KDJNSTRANS" NVARCHAR(2) NOT NULL 
		, "KDKLAIM" CHAR(2) CS_FIXEDSTRING NOT NULL 
		, "KDLAMPIRAN" CHAR(4) CS_FIXEDSTRING NOT NULL 
		, "MANDATORI" SMALLINT CS_INT DEFAULT 0
		, PRIMARY KEY ("KDPRODUK"
		, "KDKELOMPOK"
		, "KDJNSTRANS"
		, "KDKLAIM"
		, "KDLAMPIRAN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSMUTASI" 
	(
		"KDJNSMUT" SMALLINT CS_INT NOT NULL 
		, "NMJNSMUT" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, "MUTASI_PENSIUN" VARCHAR(2) DEFAULT 'N'
		, PRIMARY KEY ("KDJNSMUT")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_HITUNG" 
	(
		"KDHIT" NVARCHAR(1) NOT NULL 
		, "NMHIT" VARCHAR(44) NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDHIT")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_LAMPIRAN_SPP" 
	(
		"TGLKLAIM" LONGDATE CS_LONGDATE NOT NULL 
		, "KDHUBKEL" NVARCHAR(2) NOT NULL 
		, "NOTAS" NVARCHAR(15) NOT NULL 
		, "KDJNSTRANS" NVARCHAR(2) NOT NULL 
		, "KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "KDLAMPIRAN" NVARCHAR(4) NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("TGLKLAIM"
		, "KDHUBKEL"
		, "NOTAS"
		, "KDJNSTRANS"
		, "KDPRODUK"
		, "KDKELOMPOK"
		, "KDLAMPIRAN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_FUNGSI" 
	(
		"KDFUNGSI" SMALLINT CS_INT NOT NULL 
		, "KDAPL" SMALLINT CS_INT NOT NULL 
		, "NMFUNGSI" VARCHAR(60) NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, PRIMARY KEY ("KDFUNGSI"
		, "KDAPL")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KEJADIAN" 
	(
		"KDYMKKEJADIAN" NVARCHAR(1) NOT NULL 
		, "NMKEJADIAN" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDYMKKEJADIAN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KONV_DAPEM" 
	(
		"KDJNSDAPEM" NVARCHAR(2) NOT NULL 
		, "KDJNSPENSIUN" NVARCHAR(4) NOT NULL 
		, "KETERANGAN" VARCHAR(60)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDJNSDAPEM"
		, "KDJNSPENSIUN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_MSG" 
	(
		"KELMSG" NVARCHAR(4) NOT NULL 
		, "NOMSG" SMALLINT CS_INT NOT NULL 
		, "DESKRIPSI" VARCHAR(250)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, PRIMARY KEY ("KELMSG"
		, "NOMSG")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SIMGAJI" 
	(
		"KDCABANG" NVARCHAR(3) NOT NULL 
		, "KDDATI1" NVARCHAR(2) NOT NULL 
		, "KDDATI2" NVARCHAR(2) NOT NULL 
		, "NMDATI2" NVARCHAR(50) NOT NULL 
		, "SOSIALISASI" DATE CS_DAYDATE
		, "WORKSHOP" DATE CS_DAYDATE
		, "PARALEL" DATE CS_DAYDATE
		, "IMPLEMENTASI" DATE CS_DAYDATE
		, "PKS" DATE CS_DAYDATE
		, "KETERANGAN" VARCHAR(70)
		, "INTEGRASI" DATE CS_DAYDATE
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDCABANG"
		, "KDDATI1"
		, "KDDATI2")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_MINIMAL_HAK" 
	(
		"KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "KDKLAIM" NVARCHAR(2) NOT NULL 
		, "TMT_BERLAKU" DATE CS_DAYDATE NOT NULL 
		, "NILAI" INTEGER CS_INT DEFAULT 0
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDKELOMPOK"
		, "KDPRODUK"
		, "KDKLAIM"
		, "TMT_BERLAKU")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_APLIKASI" 
	(
		"KDAPL" INTEGER CS_INT NOT NULL 
		, "NMAPL" VARCHAR(60)
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, PRIMARY KEY ("KDAPL")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JENIS_PENERIMA_DAPEM" 
	(
		"KDJNSPENERIMA" NVARCHAR(1) NOT NULL 
		, "NMJNSPENERIMA" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KDJNSPENERIMA")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SSBP" 
	(
		"KDCABANG" NVARCHAR(3) NOT NULL 
		, "KELSSBP" NVARCHAR(1) NOT NULL 
		, "KDKPKN" NVARCHAR(10) NOT NULL 
		, "KDSSBP" NVARCHAR(3) NOT NULL 
		, "NMSSBP" VARCHAR(100) NOT NULL 
		, "KDDATI1" VARCHAR(2)
		, "KDDATI2" VARCHAR(2)
		, "KDKELOMPOK" SMALLINT CS_INT DEFAULT 1
		, "NEWCUST" VARCHAR(10)
		, "OLDCUST_ASS" VARCHAR(10)
		, "OLDCUST_PENS" VARCHAR(10)
		, "ID_ASS" VARCHAR(2)
		, "ID_PENS" VARCHAR(2)
		, "FLAG" VARCHAR(1)
		, "TMTBERLAKU" DATE CS_DAYDATE
		, "ID_JKK" VARCHAR(2)
		, "ID_JKM" VARCHAR(2)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDCABANG"
		, "KELSSBP"
		, "KDSSBP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_MASTER_IURAN" 
	(
		"KDTABEL" SMALLINT CS_INT
		, "NAMA_TABEL" VARCHAR(30)
		, "UPDSTAMP" LONGDATE CS_LONGDATE NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KDTABEL")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_PENERBIT_SKEP" 
	(
		"KDPENSKEP" NVARCHAR(60) NOT NULL 
		, "ALM_PNBTSKEP" VARCHAR(80)
		, "KOTA" VARCHAR(50)
		, "KODEPOS" VARCHAR(10)
		, "TELEPON" VARCHAR(20)
		, "KEPADA_AJUAN" VARCHAR(60)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDPENSKEP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_ESELON" 
	(
		"ECH_ECHCOD" VARCHAR(2) NOT NULL 
		, "ECH_ECHNAM" VARCHAR(5)
		, "ECH_RNKMIN" VARCHAR(2)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("ECH_ECHCOD")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSSETORPAJAK" 
	(
		"MAP" NVARCHAR(8) NOT NULL 
		, "JENIS_SETORAN" NVARCHAR(5) NOT NULL 
		, "JNS_PAJAK" INTEGER CS_INT NOT NULL 
		, "DESKRIPSI" VARCHAR(100) NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("MAP"
		, "JENIS_SETORAN"
		, "JNS_PAJAK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KELOMPOK_BAYAR" 
	(
		"KDKELBAYAR" SMALLINT CS_INT NOT NULL 
		, "NMKELBAYAR" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, "HOSTFTP" VARCHAR(30)
		, "FOLDER" VARCHAR(30)
		, "FDRDOWNLOAD" VARCHAR(30)
		, "FDRUPLOAD" VARCHAR(30)
		, "F_EDAPEM" SMALLINT CS_INT DEFAULT 0 NOT NULL 
		, "TMT_EDAPEM" DATE CS_DAYDATE
		, "TMT_LPJ" DATE CS_DAYDATE
		, "TMT_UDW" DATE CS_DAYDATE
		, "KDVENDOR" VARCHAR(10)
		, "OTENTIKASI" SMALLINT CS_INT DEFAULT 0
		, "F_LPJ" SMALLINT CS_INT DEFAULT 0 NOT NULL 
		, "F_UPD_CABANG" SMALLINT CS_INT DEFAULT 1 NOT NULL 
		, "TGLPOSTING" DATE CS_DAYDATE
		, "DESKRIPSI_EDAPEM" VARCHAR(255)
		, "F_PENYALURAN_DAPEM" SMALLINT CS_INT DEFAULT 1
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDKELBAYAR")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNS_SKEP" 
	(
		"KDJNSSKEP" SMALLINT CS_INT NOT NULL 
		, "NMJNSSKEP" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDJNSSKEP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_WLY_KERJA" 
	(
		"KDCABANG" NVARCHAR(3) NOT NULL 
		, "KDDATI1" NVARCHAR(2) NOT NULL 
		, "KDDATI2" NVARCHAR(2) NOT NULL 
		, "NMDATI2" VARCHAR(50)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, PRIMARY KEY ("KDCABANG"
		, "KDDATI1"
		, "KDDATI2")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_PERGURUAN_TINGGI" 
	(
		"KDPT" NVARCHAR(7) NOT NULL 
		, "NMPT" VARCHAR(200) NOT NULL 
		, PRIMARY KEY ("KDPT")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_TRANS" 
	(
		"TMT_TRANS" DATE CS_DAYDATE NOT NULL 
		, "KDTRANS" SMALLINT CS_INT NOT NULL 
		, "NMTRANS" VARCHAR(44)
		, "DKTRANS" SMALLINT CS_INT
		, "KDPRODUK" SMALLINT CS_INT
		, "TRRUTIN" SMALLINT CS_INT
		, "REFSAL" DECIMAL(7,2) CS_FIXED
		, "INSCALC" SMALLINT CS_INT
		, "UDW" SMALLINT CS_INT
		, "NOMINAL" INTEGER CS_INT DEFAULT 0 NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "NORUT" SMALLINT CS_INT DEFAULT 30
		, "REFINS" SMALLINT CS_INT DEFAULT 1
		, "TMT_EFEKTIF" DATE CS_DAYDATE
		, "TMT_DAPEM" DATE CS_DAYDATE
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("TMT_TRANS"
		, "KDTRANS")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_PROGRAM" 
	(
		"KODE_AREA" NVARCHAR(1) NOT NULL 
		, "NMPROGRAM" VARCHAR(44)
		, "TYPE_VOUCHER" VARCHAR(1)
		, "NMPRODUK" VARCHAR(44)
		, "TMTPROGRAM" DATE CS_DAYDATE
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KODE_AREA")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_FAKTOR_PIPNS" 
	(
		"TMT_FAKTOR" DATE CS_DAYDATE NOT NULL 
		, "KDKELOMPOK" INTEGER CS_INT NOT NULL 
		, "MI" INTEGER CS_INT NOT NULL 
		, "NILAI" DECIMAL(7,3) CS_FIXED NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("TMT_FAKTOR"
		, "KDKELOMPOK"
		, "MI")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SETORAN_KASNEG" 
	(
		"KODE_SATKER" CHAR(6) CS_FIXEDSTRING
		, "NAMA_SATKER" CHAR(100) CS_FIXEDSTRING
		, "NAMA_KEMENTRIAN" CHAR(50) CS_FIXEDSTRING
		, "KDMAP" CHAR(6) CS_FIXEDSTRING
		, "NTPN" CHAR(50) CS_FIXEDSTRING
		, "NO_SETOR" INTEGER CS_INT NOT NULL 
		, "TGL_SETOR" DATE CS_DAYDATE
		, "NOMINAL" BIGINT CS_FIXED
		, "KDCABANG" NVARCHAR(3) NOT NULL 
		, "JNS_SETOR" SMALLINT CS_INT DEFAULT 0
		, "UPDSTAMP" LONGDATE CS_LONGDATE
		, "INPUTER" VARCHAR(255) CS_FIXEDSTRING
		, PRIMARY KEY ("NO_SETOR"
		, "KDCABANG")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_INTERNAL_ORDER" 
	(
		"KDPRODUK" INTEGER CS_INT NOT NULL 
		, "KDKELOMPOK" INTEGER CS_INT NOT NULL 
		, "KDGSBER" CHAR(1) CS_FIXEDSTRING DEFAULT 'A' NOT NULL 
		, "NAMA_ORDER" VARCHAR(40)
		, PRIMARY KEY ("KDPRODUK"
		, "KDKELOMPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_BIRO" 
	(
		"KDBIRO" NVARCHAR(2) NOT NULL 
		, "KDDIRJEN" NVARCHAR(2) NOT NULL 
		, "KDINSTANSI" NVARCHAR(3) NOT NULL 
		, "NMBIRO" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32)
		, PRIMARY KEY ("KDBIRO"
		, "KDDIRJEN"
		, "KDINSTANSI")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SKEP" 
	(
		"NOSKEP" NVARCHAR(33) NOT NULL 
		, "TGLSKEP" DATE CS_DAYDATE NOT NULL 
		, "STSSKEP" SMALLINT CS_INT NOT NULL 
		, "KDSKPO" SMALLINT CS_INT
		, "TMTSKEP" DATE CS_DAYDATE NOT NULL 
		, "TMTREKAM" DATE CS_DAYDATE
		, "KDJNSSKEP" SMALLINT CS_INT NOT NULL 
		, "KDPENSKEP" VARCHAR(60) NOT NULL 
		, "TGLTERIMA" DATE CS_DAYDATE
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("NOSKEP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KMPMD_ASUMSI" 
	(
		"ID" INTEGER CS_INT GENERATED ALWAYS AS IDENTITY (START	WITH	1) NOT NULL 
		, "TMT_KMPMD" DATE CS_DAYDATE
		, "BUNGA" DECIMAL(6,4) CS_FIXED
		, "GAJI" DECIMAL(5	,4) CS_FIXED
		, "TIMESTMP" LONGDATE CS_LONGDATE NOT NULL 
		, "USERIN" INTEGER CS_INT NOT NULL 
		, "TGLCUTOFF" DATE CS_DAYDATE
		, "ISPROCESS" INTEGER CS_INT DEFAULT 0
		, PRIMARY KEY ("ID")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_DOKUMEN_TP" 
	(
		"KDDOKUMEN" SMALLINT CS_INT NOT NULL 
		, "NMDOKUMEN" CHAR(44) CS_FIXEDSTRING
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, PRIMARY KEY ("KDDOKUMEN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_ASSIGN_JABATAN" 
	(
		"TMT_JABATAN" DATE CS_DAYDATE NOT NULL 
		, "KODE_KEDUDUKAN" SMALLINT CS_INT NOT NULL 
		, "KODE_FUNGSIONAL" VARCHAR(5) NOT NULL 
		, "BUP" SMALLINT CS_INT NOT NULL 
		, "NAMA_FUNGSIONAL" VARCHAR(200) NOT NULL 
		, "TUNJANGAN_FUNGSIONAL" DECIMAL(15
		,2) CS_FIXED NOT NULL 
		, "KODE_FUNGSI" SMALLINT CS_INT NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, "INPUTER" VARCHAR(32)
		, PRIMARY KEY ("TMT_JABATAN"
		, "KODE_KEDUDUKAN"
		, "KODE_FUNGSIONAL"
		, "TUNJANGAN_FUNGSIONAL")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_HOLIDAY" 
	(
		"TGLHOLIDAY" DATE CS_DAYDATE NOT NULL 
		, "JNSHOLIDAY" SMALLINT CS_INT
		, "KETERANGAN" VARCHAR(200)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("TGLHOLIDAY")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_TRANS_JKKJKM" 
	(
		"TMT_TRANS" DATE CS_DAYDATE NOT NULL 
		, "KDTRANS" SMALLINT CS_INT NOT NULL 
		, "NMTRANS" VARCHAR(100)
		, "DKTRANS" SMALLINT CS_INT
		, "KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "KDJNSTRANS" NVARCHAR(2) NOT NULL 
		, "PROSENTASE" DECIMAL(5	,2) CS_FIXED
		, "PENGALI" INTEGER CS_INT DEFAULT 0
		, "TARIF" INTEGER CS_INT DEFAULT 0
		, "MAKSIMAL" INTEGER CS_INT DEFAULT 0
		, "TARIFSD" INTEGER CS_INT DEFAULT 0
		, "TARIFSMP" INTEGER CS_INT DEFAULT 0
		, "TARIFSMA" INTEGER CS_INT DEFAULT 0
		, "TARIFMAHASISWA" INTEGER CS_INT DEFAULT 0
		, "BERKALA" INTEGER CS_INT DEFAULT 0
		, "BLNBERKALA" INTEGER CS_INT
		, "TMT_EFEKTIF" DATE CS_DAYDATE
		, "TMT_DAPEM" DATE CS_DAYDATE
		, "NORUT" SMALLINT CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, "ANGKUTDARAT" INTEGER CS_INT DEFAULT 0
		, "ANGKUTLAUT" INTEGER CS_INT DEFAULT 0
		, "ANGKUTUDARA" INTEGER CS_INT DEFAULT 0
		, PRIMARY KEY ("TMT_TRANS"
		, "KDTRANS"
		, "KDPRODUK"
		, "KDJNSTRANS")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSHUTANG" 
	(
		"KDHUTANG" SMALLINT CS_INT NOT NULL 
		, "NMHUTANG" VARCHAR(44)
		, "RUTIN" SMALLINT CS_INT DEFAULT 1 NOT NULL 
		, "KDTRANS" SMALLINT CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KDHUTANG")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_HAKUDW" 
	(
		"TMT_HAKUDW" DATE CS_DAYDATE NOT NULL 
		, "KDJNSPENERIMA" NVARCHAR(1) NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "NILAI_UDW" INTEGER CS_INT DEFAULT 0
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, PRIMARY KEY ("TMT_HAKUDW"
		, "KDJNSPENERIMA"
		, "KDKELOMPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_LAMPIRANFORMULIR" 
	(
		"KDLAMPIRAN" NVARCHAR(4) NOT NULL 
		, "NMLAMPIRAN" VARCHAR(200) CS_FIXEDSTRING
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, PRIMARY KEY ("KDLAMPIRAN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SUMBERHUTANG" 
	(
		"KDSUMBERHUTANG" SMALLINT CS_INT NOT NULL 
		, "NMSUMBERHUTANG" VARCHAR(255)
		, "UPDSTAMP" LONGDATE CS_LONGDATE
		, "INPUTER" VARCHAR(32)
		, PRIMARY KEY ("KDSUMBERHUTANG")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_STAPEG" 
	(
		"KDSTAPEG" SMALLINT CS_INT NOT NULL 
		, "NMSTAPEG" CHAR(44) CS_FIXEDSTRING
		, "UPDSTAMP" LONGDATE CS_LONGDATE NOT NULL 
		, "INPUTER" VARCHAR(32) CS_FIXEDSTRING NOT NULL 
		, PRIMARY KEY ("KDSTAPEG")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_PRODI" 
	(
		"KDPRODI" NVARCHAR(6) NOT NULL 
		, "KDPT" NVARCHAR(7) NOT NULL 
		, "JENDINDIK" VARCHAR(10)
		, "NMPRODI" VARCHAR(100)
		, PRIMARY KEY ("KDPRODI"
		, "KDPT")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_DATI4" 
	(
		"KDDATI4" NVARCHAR(3) CS_FIXEDSTRING NOT NULL 
		, "KDDATI3" NVARCHAR(2) CS_FIXEDSTRING NOT NULL 
		, "KDDATI2" NVARCHAR(2) CS_FIXEDSTRING NOT NULL 
		, "KDDATI1" NVARCHAR(2) CS_FIXEDSTRING NOT NULL 
		, "NMDATI4" VARCHAR(60) CS_FIXEDSTRING
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, PRIMARY KEY ("KDDATI4"
		, "KDDATI3"
		, "KDDATI2"
		, "KDDATI1")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_MAP" 
	(
		"KDMAP" NVARCHAR(6)
		, "JNS_MAP" VARCHAR(1)
		, "URAIAN" VARCHAR(100)
		, "UPDSTAMP" LONGDATE CS_LONGDATE
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDMAP"
		, "JNS_MAP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_VACUM" 
	(
		"KDVACUM" SMALLINT CS_INT NOT NULL 
		, "NMVAKUM" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, PRIMARY KEY ("KDVACUM")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JENIS_HAK" 
	(
		"KDJNSHAK" NVARCHAR(1) NOT NULL 
		, "NMJNSHAK" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KDJNSHAK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_BUNGA" 
	(
		"TMT_BUNGA" DATE CS_DAYDATE NOT NULL 
		, "TINGKAT_BUNGA" DECIMAL(9,2) CS_FIXED DEFAULT 0 NOT NULL 
		, "NILAI_BUNGA" BIGINT CS_FIXED DEFAULT 0 NOT NULL 
		, "BUNGA_KONV_BULANAN" DECIMAL(15 ,10) CS_FIXED DEFAULT 0 NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, "INPUTER" VARCHAR(32)
		, PRIMARY KEY ("TMT_BUNGA")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_PRODUK" 
	(
		"KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "NMPRODUK" VARCHAR(44)
		, "TMTPRODUK" DATE CS_DAYDATE
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "TYPE_VOUCHER" SMALLINT CS_INT DEFAULT 1 NOT NULL 
		, "DAPEM" SMALLINT CS_INT DEFAULT 2
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDPRODUK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KONSTANTA" 
	(
		"NOMOR" INTEGER CS_INT NOT NULL 
		, "KONSTANTA" VARCHAR(3) NOT NULL 
		, "DESCRIPTION" VARCHAR(30)
		, "TMT_JABATAN" DATE CS_DAYDATE
		, "MAX" INTEGER CS_INT
		, "NOURUT" INTEGER CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("NOMOR")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_HUBKEL" 
	(
		"KDHUBKEL" NVARCHAR(2) NOT NULL 
		, "NMHUBKEL" VARCHAR(60)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDHUBKEL")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_PENPOK" 
	(
		"MASKER" SMALLINT CS_INT NOT NULL 
		, "JMLANAK" SMALLINT CS_INT DEFAULT 0 NOT NULL 
		, "TMT_PENPOK" DATE CS_DAYDATE NOT NULL 
		, "KDJNSPENERIMA" NVARCHAR(1) NOT NULL 
		, "KDPANGKAT" NVARCHAR(10) NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "KDSIFATPOK" NVARCHAR(1) NOT NULL 
		, "PENPOK" INTEGER CS_INT DEFAULT 0
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "MASKER_LAST" INTEGER CS_INT
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("MASKER"
		, "JMLANAK"
		, "TMT_PENPOK"
		, "KDJNSPENERIMA"
		, "KDPANGKAT"
		, "KDKELOMPOK"
		, "KDSIFATPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSTRANS" 
	(
		"KDJNSTRANS" NVARCHAR(2) NOT NULL 
		, "KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "NMJNSTRANS" NVARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDJNSTRANS"
		, "KDPRODUK"
		, "KDKELOMPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_TANGGAL_LKO" 
	(
		"TMT_AWAL" DATE CS_DAYDATE NOT NULL 
		, "TAT_AKHIR" DATE CS_DAYDATE NOT NULL 
		, "TGLRENCANA_BAYAR" DATE CS_DAYDATE NOT NULL 
		, PRIMARY KEY ("TMT_AWAL")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_FAKTOR" 
	(
		"TMT_FAKTOR" DATE CS_DAYDATE NOT NULL 
		, "TAHUN_MI" SMALLINT CS_INT NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "MASAIURAN" SMALLINT CS_INT NOT NULL 
		, "NILAI" DECIMAL(7,3) CS_FIXED
		, "NILAI1" DECIMAL(7	,3) CS_FIXED
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "KDPRODUK" SMALLINT CS_INT
		, "NILAI2" SMALLINT CS_INT
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("TMT_FAKTOR"
		, "TAHUN_MI"
		, "KDKELOMPOK"
		, "MASAIURAN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_ANUITAS" 
	(
		"TGLBERLAKU" DATE CS_DAYDATE NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "KDKLAIM" NVARCHAR(2) NOT NULL 
		, "KDSTRUKTUR" SMALLINT CS_INT NOT NULL 
		, "MASAIUR" SMALLINT CS_INT NOT NULL 
		, "NILAI" INTEGER CS_INT NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, "INPUTER" VARCHAR(32)
		, PRIMARY KEY ("TGLBERLAKU"
		, "KDKELOMPOK"
		, "KDKLAIM")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_BAGIAN" 
	(
		"KDBAG" NVARCHAR(3) NOT NULL 
		, "KDBIRO" NVARCHAR(2) NOT NULL 
		, "KDDIRJEN" NVARCHAR(2) NOT NULL 
		, "KDINSTANSI" NVARCHAR(3) NOT NULL 
		, "NMBAG" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32)
		, PRIMARY KEY ("KDBAG"
		, "KDBIRO"
		, "KDDIRJEN"
		, "KDINSTANSI")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_GAPOK" 
	(
		"MASKER" SMALLINT CS_INT NOT NULL 
		, "TMT_GAPOK" DATE CS_DAYDATE NOT NULL 
		, "KDPANGKAT" NVARCHAR(10) NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "NILAI_BAWAH" INTEGER CS_INT DEFAULT 0
		, "NILAI_ATAS" INTEGER CS_INT DEFAULT 0
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, PRIMARY KEY ("MASKER"
		, "TMT_GAPOK"
		, "KDPANGKAT"
		, "KDKELOMPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_AGAMA" 
	(
		"KDAGAMA" SMALLINT CS_INT NOT NULL 
		, "NMAGAMA" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, PRIMARY KEY ("KDAGAMA")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KELPENSIUN" 
	(
		"KDKELPENSIUN" NVARCHAR(2) NOT NULL 
		, "NMKELPENSIUN" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "MAK" VARCHAR(8)
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDKELPENSIUN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_TUNJANGAN_CACAT" 
	(
		"KDCACAT" NVARCHAR(2) NOT NULL 
		, "DESCRIPTION" VARCHAR(200)
		, "PROSENTASE" DECIMAL(16,2) CS_FIXED
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDCACAT")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSSURAT" 
	(
		"KDJNS_SURAT" NVARCHAR(2)
		, "KDPRODUK" SMALLINT CS_INT
		, "DESKRIPSI" VARCHAR(50)
		, PRIMARY KEY ("KDJNS_SURAT"
		, "KDPRODUK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KLAIM_PERSYARATAN" 
	(
		"KDKLAIM" NVARCHAR(2) NOT NULL 
		, "KDJNSTRANS" NVARCHAR(2) NOT NULL 
		, "KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "NMKLAIM" VARCHAR(75)
		, "NMSHORT" VARCHAR(8)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDKLAIM"
		, "KDJNSTRANS"
		, "KDPRODUK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SUMBERCICILAN" 
	(
		"KDSUMBERCICILAN" SMALLINT CS_INT NOT NULL 
		, "NMSUMBERCICILAN" VARCHAR(255)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KDSUMBERCICILAN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SANTUNAN_STOP" 
	(
		"KDSTOP" SMALLINT CS_INT NOT NULL 
		, "NMSTOP" CHAR(44) CS_FIXEDSTRING
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT '                                ' NOT 
		NULL 
		, PRIMARY KEY ("KDSTOP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_TAX" 
	(
		"TMTBERLAKU" DATE CS_DAYDATE NOT NULL 
		, "TAXSEQ" SMALLINT CS_INT NOT NULL 
		, "INCOME_LIMIT" DECIMAL(15		,2) CS_FIXED NOT NULL 
		, "TAXLIMIT" DECIMAL(15		,2) CS_FIXED NOT NULL 
		, "PERCENT" DECIMAL(5		,2) CS_FIXED NOT NULL 
		, "INCOME_MIN" DECIMAL(15		,2) CS_FIXED NOT NULL 
		, "KDUPD" SMALLINT CS_INT
		, "TGLINP" LONGDATE CS_LONGDATE
		, "USERINP" VARCHAR(8)
		, "TGLOTO" LONGDATE CS_LONGDATE
		, "USEROTO" VARCHAR(8)
		, "TAXSLIMIT" DECIMAL(15		,2) CS_FIXED
		, "PERCENTS" DECIMAL(7		,2) CS_FIXED
		, "INCOME_MINS" DECIMAL(15		,2) CS_FIXED
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("TMTBERLAKU"
		, "TAXSEQ")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_STS_DAMU" 
	(
		"KDSTSDAMU" SMALLINT CS_INT NOT NULL 
		, "NMSTSDAMU" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KDSTSDAMU")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KEL_KEJADIAN" 
	(
		"KDKELJADIAN" NVARCHAR(1) NOT NULL 
		, "NMKELKEJADIAN" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDKELJADIAN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_NODOSIR" 
	(
		"KDCABANG" NVARCHAR(3) NOT NULL 
		, "KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "NODOSIR" INTEGER CS_INT NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDCABANG"
		, "KDPRODUK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_BENDAHARA" 
	(
		"KDBENDAHARA" NVARCHAR(1) NOT NULL 
		, "KDCABANG" NVARCHAR(3) NOT NULL 
		, "NMBENDAHARA" VARCHAR(60)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KDBENDAHARA"
		, "KDCABANG")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSBAYAR" 
	(
		"JNSBAYAR" NVARCHAR(2) NOT NULL 
		, "KDGROUP" NVARCHAR(2) NOT NULL 
		, "KDBENDAHARA" NVARCHAR(1) NOT NULL 
		, "KDCABANG" NVARCHAR(3) NOT NULL 
		, "NMJNSBAYAR" VARCHAR(60)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32)
		, PRIMARY KEY ("JNSBAYAR"
		, "KDGROUP"
		, "KDBENDAHARA"
		, "KDCABANG")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_ASUMSI" 
	(
		"TMT_KMPMD" DATE CS_DAYDATE
		, "SUKU_BUNGA" DECIMAL(6	,4) CS_FIXED
		, "KENAIKAN_GAJI" DECIMAL(5	,4) CS_FIXED
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_NODOSIR_PUNAH" 
	(
		"KDCABANG" NVARCHAR(3) NOT NULL 
		, "KDPRODUK" INTEGER CS_INT NOT NULL 
		, "NODOSIR" INTEGER CS_INT NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, "NODOSIR_B" INTEGER CS_INT
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDCABANG"
		, "KDPRODUK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_MAP_PAJAK" 
	(
		"MAP" NVARCHAR(8) NOT NULL 
		, "DESKIRPSI" VARCHAR(30) NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("MAP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KD_TRANSAKSI" 
	(
		"KDSTATUS" NVARCHAR(2) NOT NULL 
		, "DESKRISP" VARCHAR(50)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDSTATUS")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_DATI3" 
	(
		"KDDATI3" NVARCHAR(2) CS_FIXEDSTRING NOT NULL 
		, "KDDATI2" NVARCHAR(2) CS_FIXEDSTRING NOT NULL 
		, "KDDATI1" NVARCHAR(2) CS_FIXEDSTRING NOT NULL 
		, "NMDATI3" VARCHAR(60) CS_FIXEDSTRING
		, "KTDATI3" VARCHAR(60) CS_FIXEDSTRING
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, PRIMARY KEY ("KDDATI3"
		, "KDDATI2"
		, "KDDATI1")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSDAPEM" 
	(
		"KDJNSDAPEM" NVARCHAR(2) NOT NULL 
		, "NMJENDAPEM" VARCHAR(60)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDJNSDAPEM")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSGAJI_IURAN" 
	(
		"KDJNSGAJI" SMALLINT CS_INT
		, "KETERANGAN" VARCHAR(30)
		, "UPDSTAMP" LONGDATE CS_LONGDATE NOT NULL 
		, "INPUTER" VARCHAR(32)
		, PRIMARY KEY ("KDJNSGAJI")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JENIS_KIPI" 
	(
		"JENIS" SMALLINT CS_INT NOT NULL 
		, "NM_JENIS" VARCHAR(50) NOT NULL 
		, PRIMARY KEY ("JENIS")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNS_PENERIMA" 
	(
		"KDJNSPENERIMA" NVARCHAR(1) NOT NULL 
		, "NMJNSPENERIMA" NVARCHAR(44)
		, "HAKPEN" DECIMAL(7	,2) CS_FIXED
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDJNSPENERIMA")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_DATI2" 
	(
		"KDDATI2" NVARCHAR(2) CS_FIXEDSTRING NOT NULL 
		, "KDDATI1" NVARCHAR(2) CS_FIXEDSTRING NOT NULL 
		, "NMDATI2" VARCHAR(60) CS_FIXEDSTRING
		, "KTDATI2" VARCHAR(60) CS_FIXEDSTRING
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, PRIMARY KEY ("KDDATI2"
		, "KDDATI1")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_RETSPTB" 
	(
		"KDRETSPTB" SMALLINT CS_INT NOT NULL 
		, "NMRETSPTB" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDRETSPTB")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_DANA" 
	(
		"KDCABANG" NVARCHAR(3) CS_FIXEDSTRING NOT NULL 
		, "KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "KDVOUCHER" NVARCHAR(1) CS_FIXEDSTRING NOT NULL 
		, "KDDANA" NVARCHAR(1) CS_FIXEDSTRING NOT NULL 
		, "NMDANA" VARCHAR(44)
		, "STATUS" SMALLINT CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) CS_FIXEDSTRING
		, PRIMARY KEY ("KDCABANG"
		, "KDPRODUK"
		, "KDVOUCHER"
		, "KDDANA")
	)
	UNLOAD PRIORITY 5 AUTO MERGE;;
	COMMENT ON COLUMN "TSPNMIG"."REF_DANA"."STATUS" IS '0 = TIDAK DIGUNAKAN, 1 = MASIH DIGUNAKAN';

CREATE COLUMN TABLE "TSPNMIG"."REF_BIAYA" 
	(
	"TMT_BIAYA" DATE CS_DAYDATE NOT NULL 
	, "PERSENTASE_BIAYA" DECIMAL(9,5) CS_FIXED DEFAULT 0
	, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
	, "INPUTER" VARCHAR(32)
	, PRIMARY KEY ("TMT_BIAYA")
	) 
	UNLOAD PRIORITY 5 AUTO MERGE; 

	CREATE COLUMN TABLE "TSPNMIG"."REF_DATI1" 
	(
		"KDDATI1" NVARCHAR(2) CS_FIXEDSTRING NOT NULL 
		, "NMDATI1" VARCHAR(60) CS_FIXEDSTRING
		, "KTDATI1" VARCHAR(60) CS_FIXEDSTRING
		, "TKD" DECIMAL(15,2) CS_FIXED
		, "KDTKD" SMALLINT CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, PRIMARY KEY ("KDDATI1")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_INSTANSI_TP" 
	(
		"KDINSTANSITP" NVARCHAR(1) NOT NULL 
		, "NMINSTANSITP" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDINSTANSITP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_CABANG_TP" 
	(
		"KDCABANGTP" NVARCHAR(1) NOT NULL 
		, "NMCABANGTP" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDCABANGTP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KEDUDUKAN" 
	(
		"KDDUDUKAN" SMALLINT CS_INT NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT
		, "NMDUDUKAN" VARCHAR(44)
		, "BUP_MAX" SMALLINT CS_INT
		, "BUP_MIN" SMALLINT CS_INT
		, "LEGAL" VARCHAR(50)
		, "TMT_LEGAL" DATE CS_DAYDATE
		, "PENGALI_TERUSAN" DECIMAL(7,2) CS_FIXED
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDDUDUKAN"
		, "KDKELOMPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_HITTRANS" 
	(
		"TMTHIT" DATE CS_DAYDATE NOT NULL 
		, "KDHIT" CHAR(1) CS_FIXEDSTRING NOT NULL 
		, "TMT_TRANS" DATE CS_DAYDATE NOT NULL 
		, "KDTRANS" SMALLINT CS_INT NOT NULL 
		, "KETERANGAN_HIT" VARCHAR(44) NOT NULL 
		, "KODEX" SMALLINT CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("TMTHIT"
		, "KDHIT"
		, "TMT_TRANS"
		, "KDTRANS")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_FORMULAKLIM" 
	(
		"TMT_FORMULA" DATE CS_DAYDATE NOT NULL 
		, "KDYMKKEJADIAN" NVARCHAR(1) NOT NULL 
		, "KDKELJADIAN" NVARCHAR(1) NOT NULL 
		, "KDKLAIM" NVARCHAR(2) NOT NULL 
		, "KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "KOOFISIEN1" DECIMAL(5	,4) CS_FIXED NOT NULL 
		, "KOOFISIEN2" DECIMAL(5	,4) CS_FIXED NOT NULL 
		, "ASKEM" DECIMAL(5,3) CS_FIXED NOT NULL 
		, "FAKTOR1" DECIMAL(5,3) CS_FIXED
		, "FAKTOR2" DECIMAL(5,3) CS_FIXED
		, "MANFAAT_MINIMAL" INTEGER CS_INT DEFAULT 0
		, "ASKEM_MINIMAL" INTEGER CS_INT DEFAULT 0
		, "URAIAN_FORMULA" VARCHAR(55)
		, "KETERANGAN" VARCHAR(55)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, PRIMARY KEY ("TMT_FORMULA"
		, "KDYMKKEJADIAN"
		, "KDKELJADIAN"
		, "KDKLAIM"
		, "KDPRODUK"
		, "KDKELOMPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_TPP_TKD" 
	(
		"KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "TMT_TRANS" DATE CS_DAYDATE NOT NULL 
		, "KDTRANS" SMALLINT CS_INT NOT NULL 
		, "PCTSAL" DECIMAL(7,2) CS_FIXED DEFAULT 0
		, "NOMSAL" INTEGER CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDPRODUK"
		, "KDKELOMPOK"
		, "TMT_TRANS"
		, "KDTRANS")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KLAIM" 
	(
		"KDKLAIM" NVARCHAR(2) NOT NULL 
		, "KDJNSTRANS" NVARCHAR(2) NOT NULL 
		, "KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "NMKLAIM" VARCHAR(44)
		, "NMSHORT" VARCHAR(8)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDKLAIM"
		, "KDJNSTRANS"
		, "KDPRODUK"
		, "KDKELOMPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_FORMKLIM" 
	(
		"KDPRODUK" SMALLINT CS_INT
		, "KDKLAIM" NVARCHAR(2)
		, "URAIAN" VARCHAR(150)
		, "NORUT" NVARCHAR(2)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, "ISMANDATORY" BOOLEAN CS_INT
		, PRIMARY KEY ("KDPRODUK"
		, "KDKLAIM"
		, "NORUT")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSTRANS_DAPEM" 
	(
		"KDJNSTRANS" SMALLINT CS_INT
		, "KETERANGAN" VARCHAR(30)
		, "UPDSTAMP" LONGDATE CS_LONGDATE NOT NULL 
		, "INPUTER" VARCHAR(32)
		, PRIMARY KEY ("KDJNSTRANS")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JURU_BAYAR" 
	(
		"KDKANBYR" NVARCHAR(4) NOT NULL 
		, "JNSBAYAR" NVARCHAR(2) NOT NULL 
		, "KDGROUP" NVARCHAR(2) NOT NULL 
		, "KDBENDAHARA" NVARCHAR(1) NOT NULL 
		, "KDCABANG" NVARCHAR(3) NOT NULL 
		, "NMKANBYR" VARCHAR(60)
		, "ALM_JRBYR" VARCHAR(80)
		, "KODEPOS" VARCHAR(10)
		, "TELEPON" VARCHAR(20)
		, "KDDATI2" NVARCHAR(2) NOT NULL 
		, "KDDATI1" NVARCHAR(2) NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, "NOURUT" INTEGER CS_INT
		, "KDBACKUPDPM" INTEGER CS_INT
		, "KDCEKPOS" VARCHAR(7)
		, "KDKELBAYAR" SMALLINT CS_INT NOT NULL 
		, "KODE" INTEGER CS_INT
		, "KDJURUBAYAR" VARCHAR(12)
		, "KDKPKN" VARCHAR(10) NOT NULL 
		, "STATUS" INTEGER CS_INT DEFAULT 0 NOT NULL 
		, PRIMARY KEY ("KDKANBYR"
		, "JNSBAYAR"
		, "KDGROUP"
		, "KDBENDAHARA"
		, "KDCABANG")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSUZUR" 
	(
		"JNSUZUR" SMALLINT CS_INT NOT NULL 
		, "NMUZUR" VARCHAR(50)
		, PRIMARY KEY ("JNSUZUR")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KASUS" 
	(
		"KDKASUS" SMALLINT CS_INT NOT NULL 
		, "NMKASUS" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDKASUS")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KENAIKAN_GAPOK" 
	(
		"TMT_BERLAKU" DATE CS_DAYDATE
		, "KENAIKAN" DECIMAL(5	,3) CS_FIXED NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KENAIKAN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_PANGKAT" 
	(
		"KDPANGKAT" NVARCHAR(10) NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "NMPANGKAT" VARCHAR(44)
		, "NMSHORT" VARCHAR(10)
		, "KDKONV" VARCHAR(10) NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDPANGKAT"
		, "KDKELOMPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_WILAYAH" 
	(
		"KDWILAYAH" SMALLINT CS_INT NOT NULL 
		, "NMWILAYAH" CHAR(44) CS_FIXEDSTRING
		, PRIMARY KEY ("KDWILAYAH")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KTRBYR_SETOR" 
	(
		"NOKTRSETOR" NVARCHAR(33) NOT NULL 
		, "TGLKTRSETOR" DATE CS_DAYDATE NOT NULL 
		, "KDKANBYR" CHAR(4) CS_FIXEDSTRING NOT NULL 
		, "JNSBAYAR" CHAR(2) CS_FIXEDSTRING NOT NULL 
		, "KDGROUP" CHAR(4) CS_FIXEDSTRING NOT NULL 
		, "KDBENDAHARA" CHAR(1) CS_FIXEDSTRING NOT NULL 
		, "KDCABANG" NVARCHAR(3) NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, PRIMARY KEY ("NOKTRSETOR")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SATKER" 
	(
		"KDSATKER" NVARCHAR(15) NOT NULL 
		, "KDBAG" CHAR(3) CS_FIXEDSTRING NOT NULL 
		, "KDBIRO" CHAR(2) CS_FIXEDSTRING NOT NULL 
		, "KDDIRJEN" NVARCHAR(2) NOT NULL 
		, "KDINSTANSI" NVARCHAR(3) NOT NULL 
		, "KDDATI4" CHAR(3) CS_FIXEDSTRING NOT NULL 
		, "KDDATI3" CHAR(2) CS_FIXEDSTRING NOT NULL 
		, "KDDATI2" NVARCHAR(2) NOT NULL 
		, "KDDATI1" NVARCHAR(2) NOT NULL 
		, "NMSATKER" CHAR(100) CS_FIXEDSTRING
		, "KDKPKN" CHAR(10) CS_FIXEDSTRING NOT NULL 
		, "ALAMAT" VARCHAR(255)
		, "NOTELP" CHAR(20) CS_FIXEDSTRING
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "KDCABANG" NVARCHAR(3) NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, "KDSKPD" NVARCHAR(3) NOT NULL 
		, "KDSSBP" NVARCHAR(3) NOT NULL 
		, "SATKERPEMDA" NVARCHAR(20) NOT NULL 
		, "KELSSBP" NVARCHAR(1) NOT NULL 
		, PRIMARY KEY ("KDSATKER"
		, "KDCABANG"
		, "KDSKPD"
		, "KDSSBP"
		, "SATKERPEMDA"
		, "KELSSBP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SATKER_HUTANG" 
	(
		"KDKEMENTRIAN" VARCHAR(5) NOT NULL 
		, "NMKEMENTRIAN" VARCHAR(50)
		, "KD_ESELON" VARCHAR(5)
		, "KD_SATKER" VARCHAR(8)
		, "NM_SATKER" VARCHAR(75)
		, "KDINST" VARCHAR(3) NOT NULL 
		, "NMINSTANSI" VARCHAR(75)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KASIVA" 
	(
		"KDKASIVA" NVARCHAR(4) NOT NULL 
		, "NMKASIVA" VARCHAR(44) NOT NULL 
		, "KDDATI1" NVARCHAR(2)
		, PRIMARY KEY ("KDKASIVA")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_CABANG" 
	(
		"KDCABANG" NVARCHAR(3) NOT NULL 
		, "NMCABANG" VARCHAR(44)
		, "NICKCABANG" VARCHAR(15)
		, "ALMTCABANG" VARCHAR(80)
		, "KOTA" VARCHAR(44)
		, "KODEPOS" VARCHAR(10)
		, "TELEPON" VARCHAR(20)
		, "LBLSURAT" VARCHAR(10)
		, "JMLRUANG" SMALLINT CS_INT
		, "JMLLAJUR" SMALLINT CS_INT
		, "JMLLEMARI" SMALLINT CS_INT
		, "JMLRAK" SMALLINT CS_INT
		, "JMLBOX" SMALLINT CS_INT
		, "KDWILAYAH" SMALLINT CS_INT NOT NULL 
		, "KDCABANGTP" NVARCHAR(1) NOT NULL 
		, "KDDATI1" NVARCHAR(2) NOT NULL 
		, "KDDATI2" NVARCHAR(2) NOT NULL 
		, "NOSURAT" VARCHAR(5)
		, "NOSKPP" VARCHAR(5)
		, "NOSPR" VARCHAR(5)
		, "NMKAS" VARCHAR(44)
		, "NOGIRO_THT" VARCHAR(10)
		, "NOGIRO_PENS" VARCHAR(10)
		, "NOLIMPAH" INTEGER CS_INT
		, "NOJMN" VARCHAR(10)
		, "NPWP" VARCHAR(20)
		, "HOST_RFC" VARCHAR(15)
		, "KDREFORMASI" SMALLINT CS_INT DEFAULT 0
		, "HOST_ELO" VARCHAR(15)
		, "COSTCENTRE" NVARCHAR(3)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, "HOST_ANTRI" VARCHAR(15)
		, PRIMARY KEY ("KDCABANG")
	)
	UNLOAD PRIORITY 5 AUTO MERGE;;
	COMMENT ON COLUMN "TSPNMIG"."REF_CABANG"."KDCABANG" IS 'KODE CABANG REF';

	CREATE COLUMN TABLE "TSPNMIG"."REF_MISC" 
	(
		"UPDDATE" DATE CS_DAYDATE NOT NULL 
		, "JABPCT" DECIMAL(5,2) CS_FIXED NOT NULL 
		, "JABMAX" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "PSNPCT" DECIMAL(5,2) CS_FIXED NOT NULL 
		, "PSNMAX" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "SELF" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "COUPLE" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "DEPEND" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "DEPENDMAX" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "SHF11" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "SHF12" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "SHF13" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "SHF21" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "SHF22" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "SHF23" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "SHF31" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "SHF32" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "SHF33" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "VACBON" DECIMAL(5,2) CS_FIXED NOT NULL 
		, "THRBON" DECIMAL(5,2) CS_FIXED NOT NULL 
		, "REMOTE_1" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "REMOTE_2" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "REMOTE_3" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "STBYN" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "STBYS" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "STBYH" DECIMAL(15,2) CS_FIXED NOT NULL 
		, "ASTEK" DECIMAL(5,2) CS_FIXED NOT NULL 
		, "ASTEK_COY" DECIMAL(5,2) CS_FIXED
		, "WHR_MONTH" DECIMAL(5,2) CS_FIXED NOT NULL 
		, "DAY_MONTH" DECIMAL(5,2) CS_FIXED NOT NULL 
		, "OVTWKD" DECIMAL(5,2) CS_FIXED NOT NULL 
		, "OVTNWKD" DECIMAL(5,2) CS_FIXED NOT NULL 
		, "OVTNWKD7" DECIMAL(5,2) CS_FIXED NOT NULL 
		, "INSURANCE" DECIMAL(7,6) CS_FIXED
		, "THT" DECIMAL(5,2) CS_FIXED
		, "THT_COY" DECIMAL(5,2) CS_FIXED
		, "PHT" DECIMAL(5,2) CS_FIXED
		, "PHT_COY" DECIMAL(5,2) CS_FIXED
		, "AKTK" DECIMAL(5,2) CS_FIXED
		, "AKTK_COY" DECIMAL(5,2) CS_FIXED
		, "BC" DECIMAL(5,2) CS_FIXED
		, "BC_COY" DECIMAL(5,2) CS_FIXED
		, "KDUPD" SMALLINT CS_INT
		, "TGLINP" LONGDATE CS_LONGDATE
		, "USERINP" CHAR(32) CS_FIXEDSTRING
		, "TGLOTO" LONGDATE CS_LONGDATE
		, "USEROTO" CHAR(32) CS_FIXEDSTRING
		, "OVT1" DECIMAL(7,2) CS_FIXED
		, "OVT2" DECIMAL(7,2) CS_FIXED
		, "OVT3" DECIMAL(7,2) CS_FIXED
		, "GANTI" SMALLINT CS_INT
		, "PTKPT" SMALLINT CS_INT
		, "TAXSUB" DECIMAL(15,2) CS_FIXED
		, "TAXMAX" DECIMAL(15,2) CS_FIXED
		, "OPTSHIFT" SMALLINT CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("UPDDATE")
	) 
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNS_TAGIHAN" 
	(
		"KD_JNS_TAGIHAN" INTEGER CS_INT NOT NULL 
		, "NM_JNS_TAGIHAN" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KD_JNS_TAGIHAN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SANTUNAN_CACAT" 
	(
		"KDCACAT" VARCHAR(2) NOT NULL 
		, "DESCRIPTION" VARCHAR(200)
		, "PROSENTASE" DECIMAL(26,2) CS_FIXED
		, "JNSCACAT" SMALLINT CS_INT NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, PRIMARY KEY ("KDCACAT"
		, "JNSCACAT")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KPKN" 
	(
		"KDKPKN" NVARCHAR(10) NOT NULL 
		, "KDKPPN" VARCHAR(10)
		, "NMKPKN" VARCHAR(60)
		, "ALM_KPKN" VARCHAR(80)
		, "KOTA" VARCHAR(50)
		, "KODEPOS" VARCHAR(10)
		, "TELEPON" VARCHAR(20)
		, "NOREK" VARCHAR(33)
		, "JENIS" SMALLINT CS_INT
		, "KDKASIVA" CHAR(4) CS_FIXEDSTRING NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "BANK" VARCHAR(60)
		, "KDCABANG" NVARCHAR(3)
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER NOT NULL 
		, PRIMARY KEY ("KDKPKN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_DIRJEN" 
	(
		"KDDIRJEN" NVARCHAR(2) NOT NULL 
		, "KDINSTANSI" NVARCHAR(3) NOT NULL 
		, "NMDIRJEN" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32)
		, PRIMARY KEY ("KDDIRJEN"
		, "KDINSTANSI")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_TANDAJASA" 
	(
		"KDTNDJASA" SMALLINT CS_INT NOT NULL 
		, "NMTNDJASA" VARCHAR(44)
		, "TERUSAN" SMALLINT CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDTNDJASA")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_STS_STOP" 
	(
		"KDSTOP" SMALLINT CS_INT NOT NULL 
		, "NMSTOP" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KDSTOP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSPEG" 
	(
		"KDJNSPEG" NVARCHAR(2) NOT NULL 
		, "NMJENPEG" NVARCHAR(44) NOT NULL 
		, "KODE" INTEGER CS_INT NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) CS_FIXEDSTRING NOT NULL 
		, PRIMARY KEY ("KDJNSPEG"
		, "KODE")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_INSTANSI_BKN" 
	(
		"INS_INSKOD" CHAR(4) CS_FIXEDSTRING NOT NULL 
		, "INS_NAMINS" VARCHAR(40)
		, "INS_NEWKOD" CHAR(6) CS_FIXEDSTRING
		, "KODE_LAMA" CHAR(2) CS_FIXEDSTRING
		, "JENIS" CHAR(1) CS_FIXEDSTRING
		, "LOKASI" CHAR(4) CS_FIXEDSTRING
		, "LOKER" CHAR(4) CS_FIXEDSTRING
		, "INS_KANREG" CHAR(2) CS_FIXEDSTRING
		, "INS_NAMINSBR" VARCHAR(40)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("INS_INSKOD")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_DASARBAYAR" 
	(
		"KDSURAT" SMALLINT CS_INT NOT NULL 
		, "DESKRIPSI" VARCHAR(85)
		, "F1" SMALLINT CS_INT
		, "G1" SMALLINT CS_INT
		, "G2" SMALLINT CS_INT
		, "G3" SMALLINT CS_INT
		, "G4" SMALLINT CS_INT
		, "H1" SMALLINT CS_INT
		, "J1" SMALLINT CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KDSURAT")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_LAMPIRAN_SK" 
	(
		"NMLAMPIRAN" NVARCHAR(250) NOT NULL 
		, "KDJNSTRANS" NVARCHAR(2) NOT NULL 
		, "KDPRODUK" SMALLINT CS_INT NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "KDKLAIM" NVARCHAR(2) NOT NULL 
		, "MANDATORI" SMALLINT CS_INT
		, "ASLI" SMALLINT CS_INT
		, "LEMBAR" SMALLINT CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("NMLAMPIRAN"
		, "KDJNSTRANS"
		, "KDPRODUK"
		, "KDKELOMPOK"
		, "KDKLAIM")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_GROUP" 
	(
		"KDCABANG" NVARCHAR(3) NOT NULL 
		, "KDBENDAHARA" NVARCHAR(1) NOT NULL 
		, "KDGROUP" NVARCHAR(2) NOT NULL 
		, "KDKELBAYAR" NVARCHAR(2) NOT NULL 
		, "NMGROUPTBL" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDCABANG"
		, "KDBENDAHARA"
		, "KDGROUP"
		, "KDKELBAYAR")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KELOMPOK_GAJI" 
	(
		"KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "NMKELOMPOK" VARCHAR(44)
		, "MIN_USIA_MASUK" SMALLINT CS_INT
		, "MAX_USIA_MASUK" SMALLINT CS_INT
		, "TERUSAN" SMALLINT CS_INT
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "KDNIP" VARCHAR(3) NOT NULL 
		, "UDW" SMALLINT CS_INT
		, "KDJI" SMALLINT CS_INT DEFAULT 1 NOT NULL 
		, "NORUT" SMALLINT CS_INT DEFAULT 30
		, "TMT_GAPOK1" DATE CS_DAYDATE
		, "TMT_GAPOK2" DATE CS_DAYDATE
		, "TGLRENBAYAR" DATE CS_DAYDATE
		, "TMT_GAPOK3" DATE CS_DAYDATE
		, "TGLRENBAYAR3" DATE CS_DAYDATE
		, "TMT_PENPOK" DATE CS_DAYDATE
		, "TMT_PENPOK1" DATE CS_DAYDATE
		, "TMTBYR_PENS" DATE CS_DAYDATE
		, "TMTBYR_DPM" DATE CS_DAYDATE
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, CONSTRAINT "PK" PRIMARY KEY ("KDKELOMPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_STAWIN" 
	(
		"KDSTAWIN" SMALLINT CS_INT NOT NULL 
		, "NMSTAWIN" CHAR(44) CS_FIXEDSTRING
		, "UPDSTAMP" LONGDATE CS_LONGDATE NOT NULL 
		, PRIMARY KEY ("KDSTAWIN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_INSTANSI" 
	(
		"KDINSTANSI" CHAR(3) CS_FIXEDSTRING NOT NULL 
		, "KDINSTANSITP" CHAR(1) CS_FIXEDSTRING NOT NULL 
		, "NMINSTANSI" VARCHAR(60)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) NOT NULL 
		, PRIMARY KEY ("KDINSTANSI")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KONV_PENSIUN" 
	(
		"KDJNSPENSIUN" NVARCHAR(4) NOT NULL 
		, "KETERANGAN" VARCHAR(60)
		, "KDJNSHAK" NVARCHAR(1) NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "KDSUBKELPOK" VARCHAR(1) NOT NULL 
		, "KDKELPENSIUN" VARCHAR(2) NOT NULL 
		, "KDJNSPENERIMA" NVARCHAR(1) NOT NULL 
		, "SHARINGDANA" DECIMAL(5	,2) CS_FIXED
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "KDPTKAI" SMALLINT CS_INT DEFAULT 1
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDJNSPENSIUN")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_SKPD" 
	(
		"KDCABANG" NVARCHAR(3) NOT NULL 
		, "KDSSBP" NVARCHAR(3) NOT NULL 
		, "KDSKPD" NVARCHAR(3) NOT NULL 
		, "NMSKPD" VARCHAR(100)
		, "UPDSTAMP" LONGDATE CS_LONGDATE
		, "INPUTER" VARCHAR(32) DEFAULT 'USER'
		, "KELSSBP" NVARCHAR(3) NOT NULL 
		, PRIMARY KEY ("KDCABANG"
		, "KDSSBP"
		, "KDSKPD"
		, "KELSSBP")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_TBL_BUNGA" 
	(
		"TMT_BERLAKU" DATE CS_DAYDATE NOT NULL 
		, "NILAI" DECIMAL(9,3) CS_FIXED DEFAULT 0 NOT NULL 
		, "NILAI1" DECIMAL(9,3) CS_FIXED DEFAULT 0 NOT NULL 
		, "BUNGA" DECIMAL(9,3) CS_FIXED DEFAULT 0 NOT NULL 
		, PRIMARY KEY ("TMT_BERLAKU")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_JNSKEL" 
	(
		"REF_JNSKEL_ID" INTEGER CS_INT GENERATED ALWAYS AS IDENTITY (START 
		WITH
			1) NOT NULL 
		, "KDJNSKEL" INTEGER CS_INT NOT NULL 
		, "KDSEX" VARCHAR(1) NOT NULL 
		, "NMJNSKEL" VARCHAR(20)
		, "USERIN" INTEGER CS_INT NOT NULL 
		, "TIMESTMP" LONGDATE CS_LONGDATE NOT NULL 
		, "ISDELETE" BOOLEAN CS_INT DEFAULT FALSE NOT NULL 
		, PRIMARY KEY ("KDJNSKEL")
	)
	UNLOAD PRIORITY 5 AUTO MERGE;;
	COMMENT ON COLUMN "TSPNMIG"."REF_JNSKEL"."REF_JNSKEL_ID" IS 'id generate oleh aplikasi';
	COMMENT ON COLUMN "TSPNMIG"."REF_JNSKEL"."USERIN" IS 'kode id user input';
	COMMENT ON COLUMN "TSPNMIG"."REF_JNSKEL"."TIMESTMP" IS 'Timestamp pada saat input';
	COMMENT ON COLUMN "TSPNMIG"."REF_JNSKEL"."ISDELETE" IS 'kode soft delete 0=aktif 1=data di delete';

	
CREATE COLUMN TABLE "TSPNMIG"."REF_SIFAT_POKOK" 
	(
		"KDSIFATPOK" NVARCHAR(1) NOT NULL 
		, "NMSIFATPOK" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE NOT NULL 
		, PRIMARY KEY ("KDSIFATPOK")
	) 
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_THP_KLAIM" 
	(
		"TMT_THPKLAIM" DATE CS_DAYDATE NOT NULL 
		, "KDKELOMPOK" SMALLINT CS_INT NOT NULL 
		, "RGAPOK" DECIMAL(7	,2) CS_FIXED
		, "RINSTRI" DECIMAL(7	,2) CS_FIXED
		, "RANAK" DECIMAL(7,2) CS_FIXED
		, "RPERUS" DECIMAL(7,2) CS_FIXED
		, "RSTRUK" DECIMAL(7,2) CS_FIXED
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, PRIMARY KEY ("TMT_THPKLAIM"
		, "KDKELOMPOK")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_INFOMITRA" 
	(
		"KDSTATUS" NVARCHAR(2) NOT NULL 
		, "KETERANGAN" VARCHAR(40) NOT NULL 
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDSTATUS")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_KODEPOS" 
	(
		"KODEPOS" NVARCHAR(10) NOT NULL 
		, "NOURUT" INTEGER CS_INT NOT NULL 
		, "NMKODEPOS" VARCHAR(44)
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KODEPOS"
		, "NOURUT")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."REF_WORKFLOW" 
	(
		"KDFLOW" SMALLINT CS_INT NOT NULL 
		, "NMFLOW" VARCHAR(44)
		, "KETERANGAN" CLOB MEMORY THRESHOLD 1000
		, "UPDSTAMP" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL 
		, "INPUTER" VARCHAR(32) DEFAULT CURRENT_USER
		, PRIMARY KEY ("KDFLOW")
	)
	UNLOAD PRIORITY 5 AUTO MERGE; 

CREATE COLUMN TABLE "TSPNMIG"."SURAT_PENGANTAR"  ( 
	NOSURANTAR   	NVARCHAR(33) NOT NULL,
	TGLSURATANTAR	DATE,
	KDCABANG     	NVARCHAR(3) NOT NULL,
	KDPENSKEP    	VARCHAR(60) NOT NULL,
	UPDSTAMP     	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	INPUTER      	VARCHAR(32) DEFAULT 'CURRENT_USER',
	PRIMARY KEY(NOSURANTAR,KDCABANG)
)
	UNLOAD PRIORITY 5 AUTO MERGE; 	
	
	
	
ALTER TABLE "TSPNMIG"."REF_GROUP_BAYAR" 
ADD CONSTRAINT "FKGROUPBAYAR" FOREIGN KEY ( 	"KDBENDAHARA", "KDCABANG" ) REFERENCES "TSPNMIG"."REF_BENDAHARA" ("KDBENDAHARA"	, "KDCABANG") 
	ON UPDATE	CASCADE 
	ON DELETE	RESTRICT;

ALTER TABLE "TSPNMIG"."REF_RUMAH_SAKIT" 
ADD CONSTRAINT 	"KDCABANG_45_FK" FOREIGN KEY ( "KDCABANG" ) REFERENCES "TSPNMIG"."REF_CABANG" 	("KDCABANG") 
ON UPDATE RESTRICT 
ON DELETE RESTRICT;

ALTER TABLE "TSPNMIG"."REF_FUNGSI" 
ADD CONSTRAINT "FKFUNGSI_KDAPPL"  FOREIGN KEY ( "KDAPL" ) REFERENCES "TSPNMIG"."REF_APLIKASI" ("KDAPL") 
	ON UPDATE	CASCADE 
	ON DELETE	RESTRICT;

ALTER TABLE "TSPNMIG"."REF_KONV_DAPEM" 
ADD CONSTRAINT "KDJNSDPM" FOREIGN KEY ( "KDJNSDAPEM" ) REFERENCES "TSPNMIG"."REF_JNSDAPEM" (	"KDJNSDAPEM")
ON UPDATE RESTRICT 
ON DELETE RESTRICT;

ALTER TABLE "TSPNMIG"."REF_SIMGAJI"
ADD CONSTRAINT "KDCABANG_48_FK" 	FOREIGN KEY ( "KDCABANG" ) REFERENCES "TSPNMIG"."REF_CABANG" ("KDCABANG")
ON UPDATE RESTRICT 
ON DELETE RESTRICT;

ALTER TABLE "TSPNMIG"."REF_MINIMAL_HAK"
 ADD CONSTRAINT "KDKELOMPOK_REF_MINIMAL_HAK" FOREIGN KEY ( "KDKELOMPOK" ) REFERENCES "TSPNMIG"."REF_KELOMPOK_GAJI" ("KDKELOMPOK") 
ON UPDATE RESTRICT 
ON DELETE RESTRICT;

ALTER TABLE "TSPNMIG"."REF_MINIMAL_HAK"
 ADD CONSTRAINT "KDPRODUK_REF_MINIMAL_HAK"  FOREIGN KEY ( "KDPRODUK" ) REFERENCES "TSPNMIG"."REF_PRODUK" ("KDPRODUK") 
ON UPDATE RESTRICT 
ON DELETE RESTRICT;


ALTER TABLE "TSPNMIG"."REF_SSBP"
 ADD CONSTRAINT "FKSSBPKDKPKN" 	FOREIGN KEY ( "KDKPKN" ) REFERENCES "TSPNMIG"."REF_KPKN" ("KDKPKN") 
ON UPDATE RESTRICT 
ON DELETE RESTRICT;

ALTER	TABLE "TSPNMIG"."REF_SSBP"
 ADD CONSTRAINT "FKSSBPCABANG" FOREIGN KEY ( "KDCABANG" ) REFERENCES "TSPNMIG"."REF_CABANG" ("KDCABANG")
ON UPDATE RESTRICT 
ON DELETE RESTRICT;

ALTER TABLE "TSPNMIG"."REF_JNSSETORPAJAK"
 ADD CONSTRAINT "FKMAPJNSSETORPAJAK" FOREIGN KEY ( "MAP" ) REFERENCES "TSPNMIG"."REF_MAP_PAJAK" ("MAP") 
ON UPDATE RESTRICT 
ON DELETE RESTRICT;


ALTER TABLE "TSPNMIG"."REF_TRANS"
 ADD CONSTRAINT "FKREFTRANS" FOREIGN 
	KEY ( "KDPRODUK" ) REFERENCES "TSPNMIG"."REF_PRODUK" ("KDPRODUK") 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE "TSPNMIG"."REF_SETORAN_KASNEG"
ADD CONSTRAINT 	"KDCABANG_47_FK" FOREIGN KEY ( "KDCABANG" ) REFERENCES "TSPNMIG"."REF_CABANG" 	("KDCABANG") 
ON UPDATE RESTRICT 
ON DELETE RESTRICT;

ALTER TABLE "TSPNMIG"."REF_HAKUDW"
ADD CONSTRAINT 	"FKREFHAKUDW_JNSPENERIMA" FOREIGN KEY ( "KDJNSPENERIMA" ) REFERENCES 	"TSPNMIG"."REF_JNS_PENERIMA" ("KDJNSPENERIMA") 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER	TABLE "TSPNMIG"."REF_HAKUDW"
 ADD CONSTRAINT "FKREFHAKUDW_KELOMPOKGAJI" 	FOREIGN KEY ( "KDKELOMPOK" ) REFERENCES "TSPNMIG"."REF_KELOMPOK_GAJI" (	"KDKELOMPOK") 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE "TSPNMIG"."REF_DATI4" 
ADD FOREIGN KEY ( "KDDATI3"	, "KDDATI2"	, "KDDATI1" ) REFERENCES "TSPNMIG"."REF_DATI3" ("KDDATI3"	, "KDDATI2"	, "KDDATI1") 
ON UPDATE	RESTRICT 
ON DELETE	CASCADE;

ALTER TABLE "TSPNMIG"."REF_PENPOK"
 ADD CONSTRAINT 	"FK_REF_PENPOK_KDJNSPNR" FOREIGN KEY ( "KDJNSPENERIMA" ) REFERENCES "TSPNMIG"	."REF_JNS_PENERIMA" ("KDJNSPENERIMA") 
ON UPDATE RESTRICT 
ON DELETE RESTRICT;

ALTER	TABLE "TSPNMIG"."REF_PENPOK"
 ADD CONSTRAINT "FK_REF_PENPOK_KDSIFATPOK" 	FOREIGN KEY ( "KDSIFATPOK" ) REFERENCES "TSPNMIG"."REF_SIFAT_POKOK" (	"KDSIFATPOK") 
ON UPDATE RESTRICT 
ON DELETE RESTRICT;

ALTER TABLE "TSPNMIG"."REF_FAKTOR"
 ADD CONSTRAINT "FK" FOREIGN KEY ( 	"KDKELOMPOK" ) REFERENCES "TSPNMIG"."REF_KELOMPOK_GAJI" ("KDKELOMPOK")
ON UPDATE	RESTRICT 
ON DELETE	CASCADE;


ALTER TABLE "TSPNMIG"."REF_GAPOK"
 ADD CONSTRAINT "FKREFGAPOK" FOREIGN 	KEY ( "KDPANGKAT", "KDKELOMPOK" ) REFERENCES "TSPNMIG"."REF_PANGKAT" ("KDPANGKAT"	, "KDKELOMPOK") 
ON UPDATE RESTRICT 
ON DELETE RESTRICT;

ALTER TABLE "TSPNMIG"."REF_NODOSIR"
 ADD CONSTRAINT 	"KDCABANG_REF_NODOSIR" FOREIGN KEY ( "KDCABANG" ) REFERENCES "TSPNMIG"."REF_CABANG" ("KDCABANG")
ON UPDATE RESTRICT 
ON DELETE RESTRICT;


ALTER TABLE "TSPNMIG"."REF_NODOSIR_PUNAH"
 ADD CONSTRAINT 	"KDCABANG_41_FK" FOREIGN KEY ( "KDCABANG" ) REFERENCES "TSPNMIG"."REF_CABANG" ("KDCABANG")
ON UPDATE RESTRICT 
ON DELETE RESTRICT;


ALTER TABLE "TSPNMIG"."REF_DATI3" 
ADD FOREIGN KEY ( "KDDATI2"	, "KDDATI1" ) REFERENCES "TSPNMIG"."REF_DATI2" ("KDDATI2"	, "KDDATI1")
ON UPDATE	RESTRICT 
ON DELETE	CASCADE;


ALTER TABLE "TSPNMIG"."REF_DATI2" 
ADD FOREIGN KEY ( "KDDATI1" ) 	REFERENCES "TSPNMIG"."REF_DATI1" ("KDDATI1")
ON UPDATE	RESTRICT 
ON DELETE	CASCADE;


ALTER TABLE "TSPNMIG"."REF_DANA"
 ADD CONSTRAINT "KDCABANG_28_FK"	FOREIGN KEY ( "KDCABANG" ) REFERENCES "TSPNMIG"."REF_CABANG" ("KDCABANG")
ON UPDATE RESTRICT 
ON DELETE RESTRICT;


ALTER TABLE "TSPNMIG"."REF_FORMULAKLIM"
 ADD CONSTRAINT 	"FK_REF_FORMULAKLIM" FOREIGN KEY ( "KDYMKKEJADIAN" ) REFERENCES "TSPNMIG".	"REF_KEJADIAN" ("KDYMKKEJADIAN")
ON UPDATE RESTRICT 
ON DELETE RESTRICT;


ALTER TABLE "TSPNMIG"."REF_JURU_BAYAR"
 ADD CONSTRAINT "FKREFDATI2" 	FOREIGN KEY ( "KDDATI2"	, "KDDATI1" ) REFERENCES "TSPNMIG"."REF_DATI2" ("KDDATI2"	, "KDDATI1") 
ON UPDATE	CASCADE 
ON DELETE	RESTRICT;

ALTER	TABLE "TSPNMIG"."REF_JURU_BAYAR"
 ADD CONSTRAINT "FKREFKELOMPOKBAYAR" FOREIGN 	KEY ( "KDKELBAYAR" ) REFERENCES "TSPNMIG"."REF_KELOMPOK_BAYAR" ("KDKELBAYAR") 
ON UPDATE	CASCADE 
ON DELETE	RESTRICT;

ALTER	TABLE "TSPNMIG"."REF_JURU_BAYAR"
 ADD CONSTRAINT "FKREFJNSBAYAR" FOREIGN KEY ( 	"JNSBAYAR"	, "KDGROUP"	, "KDBENDAHARA"	, "KDCABANG" ) REFERENCES "TSPNMIG"."REF_JNSBAYAR" ("JNSBAYAR"	, "KDGROUP"	, "KDBENDAHARA"	, "KDCABANG") 
 ON UPDATE CASCADE 
 ON DELETE	RESTRICT;

ALTER TABLE "TSPNMIG"."REF_PANGKAT"
 ADD CONSTRAINT 	"KDKELMPK_REF_PANGKAT" FOREIGN KEY ( "KDKELOMPOK" ) REFERENCES "TSPNMIG".	"REF_KELOMPOK_GAJI" ("KDKELOMPOK")
ON UPDATE RESTRICT 
ON DELETE RESTRICT;


ALTER TABLE "TSPNMIG"."REF_KTRBYR_SETOR"
 ADD CONSTRAINT 	"KDCABANG_35_FK" FOREIGN KEY ( "KDCABANG" ) REFERENCES "TSPNMIG"."REF_CABANG" 	("KDCABANG")
ON UPDATE RESTRICT 
ON DELETE RESTRICT;


ALTER TABLE "TSPNMIG"."REF_SATKER"
 ADD CONSTRAINT "FKSATKER_DATI1" 
	FOREIGN KEY ( "KDDATI2"	, "KDDATI1" ) REFERENCES "TSPNMIG"."REF_DATI2" ("KDDATI2"	, "KDDATI1") 
ON UPDATE	CASCADE 
ON DELETE	RESTRICT;

ALTER	TABLE "TSPNMIG"."REF_SATKER"
 ADD CONSTRAINT "FKSATKER_KDSKPD" FOREIGN KEY ( 	"KDCABANG"	, "KDSSBP"	, "KDSKPD"	, "KELSSBP" ) REFERENCES "TSPNMIG"."REF_SKPD" ("KDCABANG"	, "KDSSBP"	, "KDSKPD"	, "KELSSBP") 
 ON UPDATE	CASCADE 
ON DELETE	RESTRICT;

ALTER	TABLE "TSPNMIG"."REF_SATKER"
 ADD CONSTRAINT "FKSATKER_KDDIRJEN" FOREIGN KEY ( 	"KDDIRJEN"	, "KDINSTANSI" ) REFERENCES "TSPNMIG"."REF_DIRJEN" ("KDDIRJEN"	, "KDINSTANSI") 
 ON UPDATE	CASCADE 
ON DELETE	RESTRICT;

ALTER	TABLE "TSPNMIG"."REF_SATKER"
 ADD CONSTRAINT "KDCABANG_46_FK" FOREIGN KEY ( 	"KDCABANG" ) REFERENCES "TSPNMIG"."REF_CABANG" ("KDCABANG")
ON UPDATE RESTRICT 
ON DELETE RESTRICT;


ALTER TABLE "TSPNMIG"."REF_KASIVA" ADD FOREIGN KEY ( "KDDATI1" ) 	REFERENCES "TSPNMIG"."REF_DATI1" ("KDDATI1")
ON UPDATE RESTRICT 
ON DELETE RESTRICT;


ALTER TABLE "TSPNMIG"."REF_KONV_PENSIUN"
 ADD CONSTRAINT 	"FK_KONV_PENSIUN_KDJNSPENERIMA" FOREIGN KEY ( "KDJNSPENERIMA" ) REFERENCES 	"TSPNMIG"."REF_JNS_PENERIMA" ("KDJNSPENERIMA") 
ON UPDATE	CASCADE 
ON DELETE	RESTRICT;

ALTER	TABLE "TSPNMIG"."REF_KONV_PENSIUN"
 ADD CONSTRAINT "FK_KDJNSHAK" FOREIGN KEY ( 	"KDJNSHAK" ) REFERENCES "TSPNMIG"."REF_JENIS_HAK" ("KDJNSHAK")
 ON UPDATE RESTRICT 
ON DELETE RESTRICT;


ALTER TABLE "TSPNMIG"."REF_SKPD"
    ADD CONSTRAINT "KDSSBP_REF_SKPD" 	FOREIGN KEY ( "KDCABANG"	, "KELSSBP"	, "KDSSBP" ) REFERENCES "TSPNMIG"."REF_SSBP" ("KDCABANG"	, "KELSSBP"	, "KDSSBP")
    ON UPDATE RESTRICT 
    ON DELETE RESTRICT;

ALTER	TABLE "TSPNMIG"."REF_SKPD"
    ADD CONSTRAINT "KDCABANG_49_FK" FOREIGN KEY ( 	"KDCABANG" ) REFERENCES "TSPNMIG"."REF_CABANG" ("KDCABANG")
    ON UPDATE RESTRICT 
    ON DELETE RESTRICT;

ALTER TABLE "TSPNMIG"."ANTARA_TBL"
	ADD CONSTRAINT KDCABANG_ANTARA_TBL	FOREIGN KEY(KDCABANG)	REFERENCES TASPEN.REF_CABANG(KDCABANG)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
	
ALTER TABLE "TSPNMIG"."SURAT_PENGANTAR"
	ADD CONSTRAINT KDCABANG_51_FK FOREIGN KEY(KDCABANG) REFERENCES TASPEN.REF_CABANG(KDCABANG)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;